const express = require("express");
const cors = require("cors");
const { spawn } = require("child_process");
const ytpl = require("ytpl");
const app = express();
const fs = require("fs");
const path = require("path");

const PORT = process.env.PORT || 4000;

app.use(cors({ origin: "*", methods: ["GET", "POST"] }));
app.use(express.json());

// Đường dẫn đến file binary yt-dlp đã tải về (do script postinstall lo)
const YTDLP_PATH = path.join(__dirname, "yt-dlp");
const COOKIES_FILE_PATH = path.join(__dirname, "cookies.txt");

// --- HÀM CHUYỂN ĐỔI COOKIES (QUAN TRỌNG) ---
// Chuyển JSON (từ EditThisCookie/Extension) sang định dạng Netscape cho yt-dlp
const convertJsonToNetscape = (jsonCookies) => {
	let netscapeContent =
		"# Netscape HTTP Cookie File\n# This file is generated by the server\n\n";

	try {
		const cookies =
			typeof jsonCookies === "string"
				? JSON.parse(jsonCookies)
				: jsonCookies;

		if (!Array.isArray(cookies)) {
			console.error("Cookies không phải là dạng Array JSON.");
			return null;
		}

		cookies.forEach((c) => {
			// Xử lý các trường bắt buộc cho Netscape format
			const domain = c.domain || ".youtube.com";
			// Flag: TRUE nếu domain bắt đầu bằng dấu chấm, FALSE nếu không
			const flag = domain.startsWith(".") ? "TRUE" : "FALSE";
			const path = c.path || "/";
			const secure = c.secure ? "TRUE" : "FALSE";
			const expiration = c.expirationDate
				? Math.round(c.expirationDate)
				: 0;
			const name = c.name;
			const value = c.value;

			// Định dạng: domain \t flag \t path \t secure \t expiration \t name \t value
			netscapeContent += `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
		});

		return netscapeContent;
	} catch (e) {
		console.error("Lỗi parse JSON Cookies:", e.message);
		return null;
	}
};

// --- SETUP COOKIES KHI KHỞI ĐỘNG ---
const setupCookies = () => {
	console.log("--> Đang thiết lập Cookies...");

	// 1. Ưu tiên biến YOUTUBE_COOKIES (Dạng JSON mà bạn copy từ Extension)
	if (process.env.YOUTUBE_COOKIES) {
		console.log(
			"--> Phát hiện biến môi trường YOUTUBE_COOKIES (JSON). Đang chuyển đổi..."
		);
		const netscapeData = convertJsonToNetscape(process.env.YOUTUBE_COOKIES);
		if (netscapeData) {
			fs.writeFileSync(COOKIES_FILE_PATH, netscapeData);
			console.log(
				`--> Đã chuyển đổi và lưu cookies.txt thành công! (${netscapeData.length} bytes)`
			);
			return true;
		}
	}

	// 2. Nếu người dùng paste thẳng text dạng Netscape vào biến YOUTUBE_COOKIES_TXT
	if (process.env.YOUTUBE_COOKIES_TXT) {
		fs.writeFileSync(COOKIES_FILE_PATH, process.env.YOUTUBE_COOKIES_TXT);
		console.log("--> Đã lưu cookies.txt từ dạng text!");
		return true;
	}

	// 3. Nếu file đã tồn tại sẵn
	if (fs.existsSync(COOKIES_FILE_PATH)) {
		console.log("--> Tìm thấy file cookies.txt có sẵn trên đĩa.");
		return true;
	}

	console.log(
		"--> CẢNH BÁO: Không tìm thấy Cookies hợp lệ. Server có thể bị YouTube chặn."
	);
	return false;
};

// Chạy setup 1 lần khi server start
setupCookies();

// Helper: Chạy lệnh yt-dlp và trả về JSON
const runYtDlpInfo = (url, flags = []) => {
	return new Promise((resolve, reject) => {
		const args = [
			url,
			"--dump-single-json",
			"--no-warnings",
			"--no-check-certificates",
			"--prefer-free-formats",
			// User Agent giả lập trình duyệt Desktop để giống với Cookies đã lấy
			"--user-agent",
			"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
			...flags,
		];

		// Nếu có file cookies thì thêm vào
		if (fs.existsSync(COOKIES_FILE_PATH)) {
			args.push("--cookies", COOKIES_FILE_PATH);
		}

		const process = spawn(YTDLP_PATH, args);

		let stdout = "";
		let stderr = "";

		process.stdout.on("data", (data) => (stdout += data.toString()));
		process.stderr.on("data", (data) => (stderr += data.toString()));

		process.on("close", (code) => {
			if (code === 0) {
				try {
					const json = JSON.parse(stdout);
					resolve(json);
				} catch (e) {
					reject(new Error("Failed to parse JSON output"));
				}
			} else {
				reject(new Error(stderr || "yt-dlp exited with error"));
			}
		});
	});
};

// --- API INFO ---
app.get("/api/info", async (req, res) => {
	const { url } = req.query;
	if (!url) return res.status(400).json({ error: "Thiếu URL" });

	console.log(`--> [yt-dlp] Lấy info: ${url}`);

	try {
		const output = await runYtDlpInfo(url);

		let scriptContent = "";
		if (output.description) {
			scriptContent = output.description;
		}

		const metadata = {
			id: output.id,
			title: output.title,
			channel: output.uploader,
			views: output.view_count
				? output.view_count.toLocaleString()
				: "N/A",
			description: output.description
				? output.description.substring(0, 200) + "..."
				: "",
			thumbnailUrl: output.thumbnail,
			duration: output.duration,
			script: scriptContent || "Không có mô tả chi tiết.",
		};

		res.json(metadata);
	} catch (error) {
		console.error("yt-dlp Info Error:", error.message);

		if (error.message.includes("Sign in")) {
			return res.status(403).json({
				error: "Server bị YouTube chặn (Sign in required). Cookies có thể đã hết hạn hoặc sai IP.",
			});
		}

		res.status(500).json({ error: "Lỗi Server: " + error.message });
	}
});

// --- API PLAYLIST ---
app.get("/api/playlist", async (req, res) => {
	try {
		const { url } = req.query;
		if (!url) return res.status(400).json({ error: "Thiếu URL" });

		// Dùng ytpl cho nhanh, yt-dlp lấy playlist rất lâu
		const playlistID = await ytpl.getPlaylistID(url);
		const playlist = await ytpl(playlistID, { limit: 20 });
		const videos = playlist.items.map((item) => ({
			id: item.id,
			title: item.title,
			channel: item.author.name,
			views: "Playlist",
			description: `Playlist: ${playlist.title}`,
			thumbnailUrl: item.bestThumbnail.url,
			script: "",
		}));
		res.json(videos);
	} catch (error) {
		res.status(500).json({
			error: "Lỗi lấy Playlist (Link Mix/RD không hỗ trợ).",
		});
	}
});

// --- API DOWNLOAD ---
app.get("/api/download", async (req, res) => {
	const { url, type } = req.query;
	if (!url) return res.status(400).send("Thiếu URL");

	console.log(`--> [yt-dlp] Tải xuống: ${url} [${type}]`);

	try {
		let format = "best";
		let contentType = "video/mp4";

		if (type === "audio") {
			format = "bestaudio/best";
			contentType = "audio/mpeg";
		} else if (type === "video_silent") {
			format = "bestvideo"; // Video only (high res)
			contentType = "video/mp4";
		} else {
			// Video có tiếng (max 720p)
			format = "best[height<=720]";
			contentType = "video/mp4";
		}

		// Lấy tên file
		let title = "video";
		// Thử lấy title nhanh (nếu thất bại thì dùng tên mặc định để không chặn download)
		try {
			const info = await runYtDlpInfo(url, ["--flat-playlist"]);
			title = (info.title || "video").replace(
				/[^\w\s\u00C0-\u1EF9]/gi,
				""
			);
		} catch (e) {}

		const ext = type === "audio" ? "mp3" : "mp4";
		const filename = `${title}.${ext}`;

		res.header(
			"Content-Disposition",
			`attachment; filename*=UTF-8''${encodeURIComponent(filename)}`
		);
		res.header("Content-Type", contentType);

		const args = [
			url,
			"-o",
			"-", // Output ra stdout
			"-f",
			format,
			"--no-part",
			"--no-check-certificates",
			"--quiet",
			"--user-agent",
			"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
		];

		if (fs.existsSync(COOKIES_FILE_PATH)) {
			args.push("--cookies", COOKIES_FILE_PATH);
		}

		const subprocess = spawn(YTDLP_PATH, args);

		subprocess.stdout.pipe(res);

		subprocess.stderr.on("data", (data) => {
			// Log lỗi nhưng không crash server
			const msg = data.toString();
			if (msg.includes("ERROR")) console.error(`[yt-dlp stderr]: ${msg}`);
		});

		req.on("close", () => {
			subprocess.kill();
		});
	} catch (error) {
		console.error("Download Error:", error);
		if (!res.headersSent) res.status(500).send("Lỗi Server khi tải xuống.");
	}
});

app.get("/", (req, res) => {
	res.send("Server yt-dlp Native (v3.0) is running!");
});

app.listen(PORT, () => {
	console.log(`Server đang chạy tại port ${PORT}`);
});
